SELECT
	E.TIPO_EVENTO,
	COUNT(PE.PARTICIPANTE_CPF) AS TOTAL_PARTICIPANTES
FROM
	SYS_EVENTO.EVENTOS E
LEFT JOIN SYS_EVENTO.PARTICIPANTE_EVENTO PE ON
	E.EVENTO_ID = PE.EVENTO_ID
GROUP BY
	E.TIPO_EVENTO;