-- Comandos do MySql para exibir BD, tabelas e colunas das mesmas
-- SHOW DATABASES;
-- USE SYS_EVENTO;
-- SHOW TABLES;
-- SHOW COLUMNS FROM SYS_EVENTO.EVENTOS;
-- SHOW COLUMNS FROM SYS_EVENTO.PARTICIPANTES;

-- Cria o BD
CREATE DATABASE IF NOT EXISTS SYS_EVENTO;

-- Drop das tabelas
DROP TABLE IF EXISTS SYS_EVENTO.PARTICIPANTE_EVENTO;
DROP TABLE IF EXISTS SYS_EVENTO.PARTICIPANTES;
DROP TABLE IF EXISTS SYS_EVENTO.EVENTOS;

-- Criando as tabelas e o Relacionamento entre ambas
CREATE TABLE SYS_EVENTO.PARTICIPANTES (
	PARTICIPANTE_CPF VARCHAR(11) NOT NULL
    ,NOME_PARTICIPANTE VARCHAR(30) NOT NULL
    ,CELULAR_PARTICIPANTE VARCHAR(11) NOT NULL  
    ,PRIMARY KEY (PARTICIPANTE_CPF)
);

CREATE TABLE SYS_EVENTO.EVENTOS (
	EVENTO_ID INTEGER AUTO_INCREMENT NOT NULL
	,TIPO_EVENTO VARCHAR(30) NOT NULL
    ,DESCRICAO_EVENTO VARCHAR(200) NOT NULL
    ,DATA_EVENTO DATE NOT NULL
    ,LIMITE_PARTICIPANTES INTEGER
    ,DURACAO_EVENTO VARCHAR(15) NOT NULL
    ,PRIMARY KEY (EVENTO_ID)
);

CREATE TABLE SYS_EVENTO.PARTICIPANTE_EVENTO (
    EVENTO_ID INTEGER NOT NULL,
    PARTICIPANTE_CPF VARCHAR(11) NOT NULL,
    CONSTRAINT fk_evento FOREIGN KEY (EVENTO_ID) REFERENCES SYS_EVENTO.EVENTOS(EVENTO_ID),
    CONSTRAINT fk_participante FOREIGN KEY (PARTICIPANTE_CPF) REFERENCES SYS_EVENTO.PARTICIPANTES(PARTICIPANTE_CPF)
);

-- Concede acesso total as tabelas, para realizar conexão
-- GRANT ALL ON SYS_EVENTO.PARTICIPANTES TO SYS_EVENTO;
-- GRANT ALL ON SYS_EVENTO.EVENTOS TO SYS_EVENTO;
-- GRANT ALL ON SYS_EVENTO.PARTICIPANTE_EVENTO TO SYS_EVENTO;
